# Generated by Django 5.2.6 on 2025-09-23 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('top_product', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Sales Metric',
                'verbose_name_plural': 'Sales Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('sales_summary', 'Sales Summary'), ('recent_orders', 'Recent Orders'), ('low_stock', 'Low Stock Products'), ('top_products', 'Top Selling Products'), ('revenue_chart', 'Revenue Chart'), ('customer_map', 'Customer Map'), ('quick_stats', 'Quick Stats'), ('activity_feed', 'Activity Feed')], max_length=50)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Widget configuration settings', null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['position'],
                'unique_together': {('user', 'widget_type')},
            },
        ),
    ]
