// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuhdnyvhujechpurjveb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1aGRueXZodWplY2hwdXJqdmViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTEyMzAsImV4cCI6MjA3NDE4NzIzMH0.VsjYTpSxWFuI_SWRyP565h4piQvDd3msEmyxC0HRFmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce', // Use PKCE flow for more secure authentication
    detectSessionInUrl: true, // Detect session in URL after email verification
  }
});