# Generated by Django 5.2.6 on 2025-09-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='supabase_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
